services:
  - type: static
    name: bhogamur-jatiya-vidya-niketon
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
